# 09. 대안모형 및 강건성 분석

이 노트북은 10주차 Pivot 이후 새 가설 구조에 맞춰 대안모형 및 강건성 분석 결과를 산출한다. 직전 `08_main_model_results.ipynb`의 주모형 결과를 기준으로, Ordered Logit, 대체 DV, weighted OLS, Low DMI 하위집단, AI 측정 대체 분석에서 핵심 계수의 방향과 유의성이 유지되는지 확인한다.

이번 노트북은 **대안모형/강건성 분석만** 다루며, 주모형 결과 해석을 길게 반복하지 않는다. 모든 해석은 인과효과가 아니라 조건부 연관성 및 예비적 패턴으로 표현한다.

## 1. 설정 및 라이브러리

In [19]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.miscmodels.ordinal_model import OrderedModel
from patsy import dmatrix

try:
    from IPython.display import display, Markdown
except ImportError:
    class Markdown(str):
        pass

    def display(obj):
        print(obj)

SAVE_OUTPUTS = True

BASE_DIR = Path.cwd().resolve()
if BASE_DIR.name == "code":
    BASE_DIR = BASE_DIR.parent

DATA_CANDIDATES = [
    BASE_DIR / "working" / "analysis" / "nia_2024_analysis_total.csv",
    BASE_DIR / "working" / "featured" / "nia_2024_featured.csv",
    BASE_DIR / "working" / "cleaned" / "nia_2024_cleaned.csv",
]

OUTPUT_DIR = BASE_DIR / Path("outputs/09_alternative_robustness_models")
TABLE_DIR = OUTPUT_DIR / "tables"
MODEL_DIR = OUTPUT_DIR / "models"

MAIN_RESULT_CANDIDATES = [
    BASE_DIR / "outputs" / "08_main_model" / "tables" / "main_model_key_coefficients.xlsx",
    BASE_DIR / "outputs" / "08_main_model" / "tables" / "main_model_key_coefficients.csv",
]

if SAVE_OUTPUTS:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    MODEL_DIR.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_columns", 180)
pd.set_option("display.width", 220)

print("BASE_DIR:", BASE_DIR)
print("SAVE_OUTPUTS:", SAVE_OUTPUTS)
print("OUTPUT_DIR:", OUTPUT_DIR)

BASE_DIR: /Users/yenarue/Downloads/ITM.89912(A)/연구 데이터
SAVE_OUTPUTS: True
OUTPUT_DIR: /Users/yenarue/Downloads/ITM.89912(A)/연구 데이터/outputs/09_alternative_robustness_models

## 2. 데이터 로드 및 변수 확인

In [20]:
existing_candidates = [path for path in DATA_CANDIDATES if path.exists()]
if not existing_candidates:
    candidate_text = "\n".join(f"- {path}" for path in DATA_CANDIDATES)
    raise FileNotFoundError("분석 데이터 파일을 찾지 못했습니다. 아래 후보 경로를 확인하세요:\n" + candidate_text)

DATA_PATH = existing_candidates[0]
df = pd.read_csv(DATA_PATH, low_memory=False)
LOADED_SHAPE = df.shape

print("사용 데이터 파일:", DATA_PATH.relative_to(BASE_DIR))
print("데이터 shape:", LOADED_SHAPE)

사용 데이터 파일: working/analysis/nia_2024_analysis_total.csv
데이터 shape: (12203, 103)

In [21]:
DV_MAIN = "effect_proc_improve"
DV_ALT = "effect_average"
AI = "ai_use_sum"
AI_BINARY = "ai_use"
IT_ORG = "it_org_any"
DMI = "dmi"
INVEST_CONTROL = "it_invest_sum"
WEIGHT = "weight"
BASE_CONTROLS = ["firm_size", "industry", "region", "firm_type"]

CHECK_VARS = [DV_MAIN, DV_ALT, AI, IT_ORG, DMI, INVEST_CONTROL, "firm_size", "industry", "region", "firm_type", WEIGHT]

variable_check = pd.DataFrame([
    {
        "변수명": var,
        "존재 여부": "있음" if var in df.columns else "없음",
        "유효 N": int(df[var].notna().sum()) if var in df.columns else np.nan,
        "결측 N": int(df[var].isna().sum()) if var in df.columns else np.nan,
        "dtype": str(df[var].dtype) if var in df.columns else "해당 없음",
    }
    for var in CHECK_VARS
])

display(variable_check)

available_controls = [var for var in BASE_CONTROLS if var in df.columns]
missing_controls = [var for var in BASE_CONTROLS if var not in df.columns]
if missing_controls:
    warnings.warn("일부 통제변수가 없어 해당 변수는 제외합니다: " + ", ".join(missing_controls))
if "firm_size" not in df.columns or "industry" not in df.columns:
    warnings.warn("핵심 통제변수 firm_size 또는 industry가 누락되었습니다.")

needed_base = [DV_MAIN, AI, IT_ORG, DMI, INVEST_CONTROL] + available_controls
analysis_vars = sorted(set([var for var in [DV_MAIN, DV_ALT, AI, AI_BINARY, IT_ORG, DMI, INVEST_CONTROL, WEIGHT] + available_controls if var in df.columns]))
analysis_df = df[analysis_vars].copy()
for var in analysis_vars:
    analysis_df[var] = pd.to_numeric(analysis_df[var], errors="coerce")

print("사용 통제변수:", available_controls)
if WEIGHT not in analysis_df.columns:
    warnings.warn("weight 변수가 없어 weighted OLS는 건너뜁니다.")

                    변수명 존재 여부   유효 N  결측 N    dtype
0   effect_proc_improve    있음  12203     0    int64
1        effect_average    있음  12203     0  float64
2            ai_use_sum    있음  12203     0    int64
3            it_org_any    있음  12203     0    int64
4                   dmi    있음  12203     0    int64
5         it_invest_sum    있음  12203     0    int64
6             firm_size    있음  12203     0    int64
7              industry    있음  12203     0    int64
8                region    있음  12203     0    int64
9             firm_type    있음  12203     0    int64
10               weight    있음  12203     0  float64

사용 통제변수: ['firm_size', 'industry', 'region', 'firm_type']

## 3. 수행할 보조모형 목록

In [22]:
robustness_plan = pd.DataFrame([
    {"분석 구분": "Main OLS 기준", "내용": "08번 주모형 결과 파일이 있으면 로드, 없으면 OLS HC3 재추정", "수행 여부": "수행"},
    {"분석 구분": "Ordered Logit", "내용": "순서형 DV 대안모형", "수행 여부": "변수 존재 및 수렴 시 수행"},
    {"분석 구분": "Alternative DV OLS", "내용": "DV를 effect_average로 대체", "수행 여부": "effect_average 존재 시 수행"},
    {"분석 구분": "Weighted OLS", "내용": "weight 적용 WLS HC3", "수행 여부": "weight 존재 시 수행"},
    {"분석 구분": "Low DMI Subsample", "내용": "Low DMI 하위집단 OLS HC3", "수행 여부": "dmi 존재 시 수행"},
    {"분석 구분": "Alternative AI Measure", "내용": "ai_use × it_org_any 보조 분석", "수행 여부": "ai_use 존재 시 수행"},
])
display(robustness_plan)

                    분석 구분                                      내용                   수행 여부
0             Main OLS 기준  08번 주모형 결과 파일이 있으면 로드, 없으면 OLS HC3 재추정                      수행
1           Ordered Logit                             순서형 DV 대안모형         변수 존재 및 수렴 시 수행
2      Alternative DV OLS                  DV를 effect_average로 대체  effect_average 존재 시 수행
3            Weighted OLS                       weight 적용 WLS HC3          weight 존재 시 수행
4       Low DMI Subsample                    Low DMI 하위집단 OLS HC3             dmi 존재 시 수행
5  Alternative AI Measure               ai_use × it_org_any 보조 분석          ai_use 존재 시 수행

## 4. 공통 함수

In [23]:
RESULT_ROWS = []
FIT_ROWS = []
MAIN_FULL_SUMMARIES = []
FULL_SUMMARIES = []
TABLES = {}


def control_formula(controls: list[str]) -> str:
    terms = []
    for var in controls:
        if var == "firm_size":
            terms.append("firm_size")
        elif var in ["industry", "region", "firm_type"]:
            terms.append(f"C({var})")
        else:
            terms.append(var)
    return " + ".join(terms)

CONTROL_TERMS = control_formula(available_controls)
CONTROL_SUFFIX = f" + {CONTROL_TERMS}" if CONTROL_TERMS else ""


def p_stars(p_value: float) -> str:
    if pd.isna(p_value):
        return ""
    if p_value < 0.001:
        return "***"
    if p_value < 0.01:
        return "**"
    if p_value < 0.05:
        return "*"
    return ""


def direction(coef: float) -> str:
    if pd.isna(coef):
        return ""
    return "+" if coef > 0 else "-" if coef < 0 else "0"


def is_sig(p_value: float) -> bool | None:
    if pd.isna(p_value):
        return None
    return bool(p_value < 0.05)


def format_coef_with_stars(coef: float, se: float, p_value: float) -> str:
    if pd.isna(coef):
        return ""
    return f"{coef:.3f}{p_stars(p_value)}\n({se:.3f})"



def full_summary_text(model_name: str, estimator: str, formula: str, model) -> str:
    summary = str(model.summary()) if model is not None else "Model was not estimated."
    return (
        "=" * 100
        + f"\n{model_name}\n"
        + f"Estimator: {estimator}\n"
        + f"Formula: {formula}\n"
        + "=" * 100
        + "\n"
        + summary
    )

def fit_ols_hc3(formula: str, data: pd.DataFrame):
    model_data = data.dropna().copy()
    if model_data.empty:
        return None, model_data, "no complete-case data"
    try:
        result = smf.ols(formula, data=model_data).fit(cov_type="HC3")
        return result, model_data, "ok"
    except Exception as exc:
        return None, model_data, str(exc)


def fit_wls_hc3(formula: str, data: pd.DataFrame, weight_col: str):
    model_data = data.dropna().copy()
    model_data = model_data[model_data[weight_col] > 0].copy()
    if model_data.empty:
        return None, model_data, "no positive-weight complete-case data"
    try:
        result = smf.wls(formula, data=model_data, weights=model_data[weight_col]).fit(cov_type="HC3")
        return result, model_data, "ok"
    except Exception as exc:
        return None, model_data, str(exc)


def ordered_design_data(formula_rhs: str, data: pd.DataFrame, y_col: str):
    model_data = data.dropna().copy()
    y = model_data[y_col].astype(int)
    # Keep patsy's treatment coding, then remove the explicit intercept. This avoids a full set of category dummies.
    exog = dmatrix(formula_rhs, data=model_data, return_type="dataframe")
    if "Intercept" in exog.columns:
        exog = exog.drop(columns=["Intercept"])
    # OrderedModel must not include an intercept-like constant. Drop any remaining all-one columns defensively.
    constant_cols = [col for col in exog.columns if exog[col].nunique(dropna=False) == 1]
    if constant_cols:
        exog = exog.drop(columns=constant_cols)
    return model_data, y, exog


def fit_ordered_logit(y_col: str, rhs: str, data: pd.DataFrame):
    try:
        model_data, y, exog = ordered_design_data(rhs, data, y_col)
        if len(model_data) == 0:
            return None, model_data, "no complete-case data"
        model = OrderedModel(y, exog, distr="logit")
        result = model.fit(method="bfgs", disp=False, maxiter=500)
        return result, model_data, "ok"
    except Exception as exc:
        return None, pd.DataFrame(), str(exc)


def extract_result(model, term: str, model_type: str):
    if model is None or term not in model.params.index:
        return {"coef": np.nan, "se": np.nan, "p": np.nan, "stars": "", "direction": ""}
    coef = float(model.params[term])
    if hasattr(model, "bse") and term in model.bse.index:
        se = float(model.bse[term])
    else:
        se = np.nan
    if hasattr(model, "pvalues") and term in model.pvalues.index:
        p_value = float(model.pvalues[term])
    else:
        p_value = np.nan
    return {"coef": coef, "se": se, "p": p_value, "stars": p_stars(p_value), "direction": direction(coef)}


def fit_value(model, model_type: str):
    if model is None:
        return ""
    if model_type in ["OLS", "WLS", "Subsample OLS"]:
        return f"R² = {model.rsquared:.3f}, Adj. R² = {model.rsquared_adj:.3f}"
    if model_type == "Ordered Logit":
        return f"Log-likelihood = {model.llf:.1f}, AIC = {model.aic:.1f}, BIC = {model.bic:.1f}"
    return ""


def model_n(model, model_data: pd.DataFrame):
    if model is not None and hasattr(model, "nobs"):
        return int(model.nobs)
    return int(len(model_data))


def compare_with_main(row_direction, row_sig, main_ref):
    if main_ref is None:
        return "기준 없음", "기준 없음"
    direction_match = "일치" if row_direction == main_ref.get("direction") else "불일치"
    sig_match = "일치" if row_sig == main_ref.get("sig") else "불일치"
    return direction_match, sig_match


def conclusion(direction_match, sig_match, analysis_group):
    if analysis_group == "Low DMI Subsample":
        return "탐색적 결과"
    if direction_match == "일치" and sig_match == "일치":
        return "주모형과 방향·유의성 일치"
    if direction_match == "일치" and sig_match != "일치":
        return "방향은 일치하나 유의성은 약함"
    if direction_match == "불일치":
        return "방향 불일치"
    return "보조분석에서만 확인"


def add_result(analysis_group, hypothesis, model_name, dv, term, model, model_data, model_type, note, main_key=None):
    tr = extract_result(model, term, model_type)
    row_sig = is_sig(tr["p"])
    main_ref = MAIN_REFERENCE.get(main_key or f"{hypothesis}|{term}") if "MAIN_REFERENCE" in globals() else None
    direction_match, sig_match = compare_with_main(tr["direction"], row_sig, main_ref)
    row = {
        "가설": hypothesis,
        "분석 구분": analysis_group,
        "모형명": model_name,
        "종속변수": dv,
        "핵심 계수": term,
        "계수": tr["coef"],
        "표준오차": tr["se"],
        "p-value": tr["p"],
        "유의수준": tr["stars"],
        "N": model_n(model, model_data),
        "적합도": fit_value(model, model_type),
        "방향": tr["direction"],
        "주모형 방향과 일치 여부": direction_match,
        "주모형 유의성과 일치 여부": sig_match,
        "결론": conclusion(direction_match, sig_match, analysis_group),
        "비고": note,
    }
    RESULT_ROWS.append(row)
    return row


def add_fit(model_name, analysis_group, model_type, model, model_data, status):
    FIT_ROWS.append({
        "분석 구분": analysis_group,
        "모형명": model_name,
        "모형 유형": model_type,
        "N": model_n(model, model_data),
        "상태": status,
        "적합도": fit_value(model, model_type),
        "AIC": getattr(model, "aic", np.nan) if model is not None else np.nan,
        "BIC": getattr(model, "bic", np.nan) if model is not None else np.nan,
        "R²": getattr(model, "rsquared", np.nan) if model is not None else np.nan,
        "Adj. R²": getattr(model, "rsquared_adj", np.nan) if model is not None else np.nan,
    })


def display_note(title: str, lines: list[str]) -> None:
    display(Markdown("**" + title + "**\n" + "\n".join(f"- {line}" for line in lines)))

## 5. 주모형 기준 결과표

In [24]:
MAIN_REFERENCE = {}
main_ref_loaded = False
main_ref_path = next((path for path in MAIN_RESULT_CANDIDATES if path.exists()), None)

if main_ref_path is not None:
    try:
        if main_ref_path.suffix.lower() == ".xlsx":
            main_ref_df = pd.read_excel(main_ref_path)
        else:
            main_ref_df = pd.read_csv(main_ref_path)
        main_ref_loaded = True
        print("주모형 결과 파일 로드:", main_ref_path.relative_to(BASE_DIR))
        display(main_ref_df)
    except Exception as exc:
        warnings.warn(f"주모형 결과 파일 로드 실패, 재추정으로 진행합니다: {exc}")
        main_ref_loaded = False

MAIN_SPECS = {
    "H1 Main OLS": (DV_MAIN, f"{DV_MAIN} ~ {AI}{CONTROL_SUFFIX}", "H1", AI, "H1|ai_use_sum"),
    "H2 Headline Main OLS": (DV_MAIN, f"{DV_MAIN} ~ {AI} + {IT_ORG} + {INVEST_CONTROL} + {AI}:{IT_ORG}{CONTROL_SUFFIX}", "H2 Headline", f"{AI}:{IT_ORG}", "H2 Headline|ai_use_sum:it_org_any"),
    "H3 Main OLS": (DV_MAIN, f"{DV_MAIN} ~ {AI} + {DMI} + {AI}:{DMI}{CONTROL_SUFFIX}", "H3", f"{AI}:{DMI}", "H3|ai_use_sum:dmi"),
    "Integrated Main OLS H2": (DV_MAIN, f"{DV_MAIN} ~ {AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", "Integrated H2", f"{AI}:{IT_ORG}", "Integrated H2|ai_use_sum:it_org_any"),
    "Integrated Main OLS H3": (DV_MAIN, f"{DV_MAIN} ~ {AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", "Integrated H3", f"{AI}:{DMI}", "Integrated H3|ai_use_sum:dmi"),
}

main_reference_rows = []
MAIN_MODELS = {}
MAIN_MODEL_FORMULAS = {}
for model_name, (dv, formula, hypothesis, term, ref_key) in MAIN_SPECS.items():
    model_vars = sorted(set([dv, AI, IT_ORG, DMI, INVEST_CONTROL] + available_controls))
    model, model_data, status = fit_ols_hc3(formula, analysis_df[[var for var in model_vars if var in analysis_df.columns]])
    MAIN_MODELS[model_name] = model
    MAIN_MODEL_FORMULAS[model_name] = formula
    if model is not None:
        MAIN_FULL_SUMMARIES.append(full_summary_text(model_name, "OLS HC3", formula, model))
    tr = extract_result(model, term, "OLS")
    MAIN_REFERENCE[ref_key] = {"direction": tr["direction"], "sig": is_sig(tr["p"]), "coef": tr["coef"], "p": tr["p"]}
    main_reference_rows.append({
        "가설": hypothesis,
        "분석 구분": "Main OLS 기준",
        "모형명": model_name,
        "종속변수": dv,
        "핵심 계수": term,
        "계수": tr["coef"],
        "표준오차": tr["se"],
        "p-value": tr["p"],
        "유의수준": tr["stars"],
        "N": model_n(model, model_data),
        "적합도": fit_value(model, "OLS"),
        "방향": tr["direction"],
        "주모형 방향과 일치 여부": "기준",
        "주모형 유의성과 일치 여부": "기준",
        "결론": "주모형 기준",
        "비고": "비교 기준값",
    })
    add_fit(model_name, "Main OLS 기준", "OLS", model, model_data, status)

main_reference_table = pd.DataFrame(main_reference_rows)
for col in ["계수", "표준오차", "p-value"]:
    main_reference_table[col] = main_reference_table[col].round(4)
display(main_reference_table)
TABLES["main_reference"] = main_reference_table

주모형 결과 파일 로드: outputs/08_main_model/tables/main_model_key_coefficients.xlsx

            가설                                모형                 종속변수                  핵심 변수      계수  HC3 Robust SE  p-value 유의수준      N      R²  Adj. R² 해석 방향                                 비고
0           H1                       H1 Baseline  effect_proc_improve             ai_use_sum  0.0521         0.0056   0.0000  ***  12203  0.1125   0.1100     +               AI 활용 범위와 DV의 기본 관련성
1     H2 Basic             H2 Basic: AI × IT org  effect_proc_improve  ai_use_sum:it_org_any  0.0638         0.0109   0.0000  ***  12203  0.1247   0.1221     +      AI 활용 범위와 IT 조직 보유의 기본 결합 관련성
2  H2 Headline  H2 Headline: Model D replication  effect_proc_improve             ai_use_sum -0.0237         0.0090   0.0085   **  12203  0.1480   0.1454     -  정보화 투자 범위 통제 후 AI 활용 범위의 단독 계수 방향
3  H2 Headline  H2 Headline: Model D replication  effect_proc_improve             it_org_any  0.0110         0.0175   0.5274  NaN  12203  0.1480   0.1454     +  정보화 투자 범위 통제 후 IT 조직 보유의 단독 계수 방향
4  H2 Headline  H2 Headline: Model D replication  effect_proc_improve  ai_use_sum:it_org_any  0.0575         0.0107   0.0000  ***  12203  0.1480   0.1454     +      정보화 투자 범위 통제 후 상호작용항 유지 여부 확인
5           H3                      H3: AI × DMI  effect_proc_improve         ai_use_sum:dmi  0.0004         0.0007   0.6233  NaN  12203  0.1265   0.1239     +              AI 활용 범위와 DMI의 결합 관련성
6   Integrated  Integrated Complementarity Model  effect_proc_improve  ai_use_sum:it_org_any  0.0601         0.0119   0.0000  ***  12203  0.1508   0.1481     +   두 보완재 동시 포함 후 AI × IT 조직 항 유지 여부
7   Integrated  Integrated Complementarity Model  effect_proc_improve         ai_use_sum:dmi -0.0015         0.0008   0.0661  NaN  12203  0.1508   0.1481     -        두 보완재 동시 포함 후 AI × DMI 항 방향

              가설        분석 구분                     모형명                 종속변수                  핵심 계수      계수    표준오차  p-value 유의수준      N                          적합도 방향 주모형 방향과 일치 여부 주모형 유의성과 일치 여부      결론      비고
0             H1  Main OLS 기준             H1 Main OLS  effect_proc_improve             ai_use_sum  0.0521  0.0056   0.0000  ***  12203  R² = 0.112, Adj. R² = 0.110  +            기준             기준  주모형 기준  비교 기준값
1    H2 Headline  Main OLS 기준    H2 Headline Main OLS  effect_proc_improve  ai_use_sum:it_org_any  0.0575  0.0107   0.0000  ***  12203  R² = 0.148, Adj. R² = 0.145  +            기준             기준  주모형 기준  비교 기준값
2             H3  Main OLS 기준             H3 Main OLS  effect_proc_improve         ai_use_sum:dmi  0.0004  0.0007   0.6233       12203  R² = 0.126, Adj. R² = 0.124  +            기준             기준  주모형 기준  비교 기준값
3  Integrated H2  Main OLS 기준  Integrated Main OLS H2  effect_proc_improve  ai_use_sum:it_org_any  0.0601  0.0119   0.0000  ***  12203  R² = 0.151, Adj. R² = 0.148  +            기준             기준  주모형 기준  비교 기준값
4  Integrated H3  Main OLS 기준  Integrated Main OLS H3  effect_proc_improve         ai_use_sum:dmi -0.0015  0.0008   0.0661       12203  R² = 0.151, Adj. R² = 0.148  -            기준             기준  주모형 기준  비교 기준값

## 6. Robustness A: Ordered Logit

In [25]:
ORDERED_SPECS = [
    ("H1 Ordered Logit", "H1", DV_MAIN, f"{AI}{CONTROL_SUFFIX}", AI, "H1|ai_use_sum", "순서형 DV 대안모형"),
    ("H2 Headline Ordered Logit", "H2 Headline", DV_MAIN, f"{AI} + {IT_ORG} + {INVEST_CONTROL} + {AI}:{IT_ORG}{CONTROL_SUFFIX}", f"{AI}:{IT_ORG}", "H2 Headline|ai_use_sum:it_org_any", "H2 headline의 Ordered Logit 확인"),
    ("H3 Ordered Logit", "H3", DV_MAIN, f"{AI} + {DMI} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{DMI}", "H3|ai_use_sum:dmi", "H3 Ordered Logit 확인"),
    ("Integrated Ordered Logit H2", "Integrated H2", DV_MAIN, f"{AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{IT_ORG}", "Integrated H2|ai_use_sum:it_org_any", "통합 Ordered Logit의 H2 항"),
    ("Integrated Ordered Logit H3", "Integrated H3", DV_MAIN, f"{AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{DMI}", "Integrated H3|ai_use_sum:dmi", "통합 Ordered Logit의 H3 항"),
]

ordered_rows_before = len(RESULT_ROWS)
for model_name, hypothesis, dv, rhs, term, ref_key, note in ORDERED_SPECS:
    required = sorted(set([dv, AI, IT_ORG, DMI, INVEST_CONTROL] + available_controls))
    missing = [var for var in required if var not in analysis_df.columns]
    if missing:
        warnings.warn(f"{model_name} 건너뜀: 누락 변수 {missing}")
        continue
    model, model_data, status = fit_ordered_logit(dv, rhs, analysis_df[required])
    add_fit(model_name, "Ordered Logit", "Ordered Logit", model, model_data, status)
    if model is not None:
        ordered_formula = f"{dv} ~ {rhs}"
        FULL_SUMMARIES.append(full_summary_text(model_name, "Ordered Logit", ordered_formula, model))
        add_result("Ordered Logit", hypothesis, model_name, dv, term, model, model_data, "Ordered Logit", note, ref_key)
    else:
        warnings.warn(f"{model_name} 수렴/추정 실패: {status}")

ordered_logit_table = pd.DataFrame(RESULT_ROWS[ordered_rows_before:])
for col in ["계수", "표준오차", "p-value"]:
    if col in ordered_logit_table:
        ordered_logit_table[col] = ordered_logit_table[col].round(4)
display(ordered_logit_table)
TABLES["ordered_logit"] = ordered_logit_table

,가설,분석 구분,모형명,종속변수,핵심 계수,계수,표준오차,p-value,유의수준,N,적합도,방향,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론,비고
0,H1,Ordered Logit,H1 Ordered Logit,effect_proc_improve,ai_use_sum,0.1471,0.0152,0.0000,***,12203,"Log-likelihood = -12984.5, AIC = 26044.9, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,순서형 DV 대안모형
1,H2 Headline,Ordered Logit,H2 Headline Ordered Logit,effect_proc_improve,ai_use_sum:it_org_any,0.1933,0.0294,0.0000,***,12203,"Log-likelihood = -12728.8, AIC = 25539.5, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,H2 headline의 Ordered Logit 확인
2,H3,Ordered Logit,H3 Ordered Logit,effect_proc_improve,ai_use_sum:dmi,0.0047,0.0026,0.0632,,12203,"Log-likelihood = -12872.7, AIC = 25825.3, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,H3 Ordered Logit 확인
3,Integrated H2,Ordered Logit,Integrated Ordered Logit H2,effect_proc_improve,ai_use_sum:it_org_any,0.1851,0.0316,0.0000,***,12203,"Log-likelihood = -12705.4, AIC = 25496.8, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,통합 Ordered Logit의 H2 항
4,Integrated H3,Ordered Logit,Integrated Ordered Logit H3,effect_proc_improve,ai_use_sum:dmi,-0.0014,0.0027,0.5947,,12203,"Log-likelihood = -12705.4, AIC = 25496.8, BIC ...",-,일치,일치,주모형과 방향·유의성 일치,통합 Ordered Logit의 H3 항

## 7. Robustness B: 대체 DV OLS

In [26]:
ALT_DV_SPECS = [
    ("H1 Alternative DV OLS", "H1", DV_ALT, f"{DV_ALT} ~ {AI}{CONTROL_SUFFIX}", AI, "H1|ai_use_sum", "대체 DV에서 H1 방향 확인"),
    ("H2 Headline Alternative DV OLS", "H2 Headline", DV_ALT, f"{DV_ALT} ~ {AI} + {IT_ORG} + {INVEST_CONTROL} + {AI}:{IT_ORG}{CONTROL_SUFFIX}", f"{AI}:{IT_ORG}", "H2 Headline|ai_use_sum:it_org_any", "대체 DV에서 H2 headline 확인"),
    ("H3 Alternative DV OLS", "H3", DV_ALT, f"{DV_ALT} ~ {AI} + {DMI} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{DMI}", "H3|ai_use_sum:dmi", "대체 DV에서 H3 확인"),
    ("Integrated Alternative DV OLS H2", "Integrated H2", DV_ALT, f"{DV_ALT} ~ {AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{IT_ORG}", "Integrated H2|ai_use_sum:it_org_any", "대체 DV 통합모형 H2 항"),
    ("Integrated Alternative DV OLS H3", "Integrated H3", DV_ALT, f"{DV_ALT} ~ {AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{DMI}", "Integrated H3|ai_use_sum:dmi", "대체 DV 통합모형 H3 항"),
]

alt_rows_before = len(RESULT_ROWS)
if DV_ALT not in analysis_df.columns:
    warnings.warn("effect_average가 없어 대체 DV 분석을 건너뜁니다.")
else:
    for model_name, hypothesis, dv, formula, term, ref_key, note in ALT_DV_SPECS:
        required = sorted(set([dv, AI, IT_ORG, DMI, INVEST_CONTROL] + available_controls))
        model, model_data, status = fit_ols_hc3(formula, analysis_df[[var for var in required if var in analysis_df.columns]])
        add_fit(model_name, "Alternative DV OLS", "OLS", model, model_data, status)
        if model is not None:
            FULL_SUMMARIES.append(full_summary_text(model_name, "OLS HC3", formula, model))
            add_result("Alternative DV OLS", hypothesis, model_name, dv, term, model, model_data, "OLS", note, ref_key)
        else:
            warnings.warn(f"{model_name} 추정 실패: {status}")

alternative_dv_table = pd.DataFrame(RESULT_ROWS[alt_rows_before:])
for col in ["계수", "표준오차", "p-value"]:
    if col in alternative_dv_table:
        alternative_dv_table[col] = alternative_dv_table[col].round(4)
display(alternative_dv_table)
TABLES["alternative_dv"] = alternative_dv_table

,가설,분석 구분,모형명,종속변수,핵심 계수,계수,표준오차,p-value,유의수준,N,적합도,방향,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론,비고
0,H1,Alternative DV OLS,H1 Alternative DV OLS,effect_average,ai_use_sum,0.0557,0.0045,0.0000,***,12203,"R² = 0.199, Adj. R² = 0.196",+,일치,일치,주모형과 방향·유의성 일치,대체 DV에서 H1 방향 확인
1,H2 Headline,Alternative DV OLS,H2 Headline Alternative DV OLS,effect_average,ai_use_sum:it_org_any,0.0739,0.0081,0.0000,***,12203,"R² = 0.265, Adj. R² = 0.263",+,일치,일치,주모형과 방향·유의성 일치,대체 DV에서 H2 headline 확인
2,H3,Alternative DV OLS,H3 Alternative DV OLS,effect_average,ai_use_sum:dmi,0.0015,0.0006,0.0072,**,12203,"R² = 0.245, Adj. R² = 0.243",+,일치,불일치,방향은 일치하나 유의성은 약함,대체 DV에서 H3 확인
3,Integrated H2,Alternative DV OLS,Integrated Alternative DV OLS H2,effect_average,ai_use_sum:it_org_any,0.0676,0.0090,0.0000,***,12203,"R² = 0.282, Adj. R² = 0.280",+,일치,일치,주모형과 방향·유의성 일치,대체 DV 통합모형 H2 항
4,Integrated H3,Alternative DV OLS,Integrated Alternative DV OLS H3,effect_average,ai_use_sum:dmi,-0.0006,0.0006,0.3523,,12203,"R² = 0.282, Adj. R² = 0.280",-,일치,일치,주모형과 방향·유의성 일치,대체 DV 통합모형 H3 항

## 8. Robustness C: Weighted OLS

In [27]:
WEIGHTED_SPECS = [
    ("H1 Weighted OLS", "H1", DV_MAIN, f"{DV_MAIN} ~ {AI}{CONTROL_SUFFIX}", AI, "H1|ai_use_sum", "가중치 적용 H1"),
    ("H2 Headline Weighted OLS", "H2 Headline", DV_MAIN, f"{DV_MAIN} ~ {AI} + {IT_ORG} + {INVEST_CONTROL} + {AI}:{IT_ORG}{CONTROL_SUFFIX}", f"{AI}:{IT_ORG}", "H2 Headline|ai_use_sum:it_org_any", "가중치 적용 H2 headline"),
    ("H3 Weighted OLS", "H3", DV_MAIN, f"{DV_MAIN} ~ {AI} + {DMI} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{DMI}", "H3|ai_use_sum:dmi", "가중치 적용 H3"),
    ("Integrated Weighted OLS H2", "Integrated H2", DV_MAIN, f"{DV_MAIN} ~ {AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{IT_ORG}", "Integrated H2|ai_use_sum:it_org_any", "가중치 적용 통합모형 H2 항"),
    ("Integrated Weighted OLS H3", "Integrated H3", DV_MAIN, f"{DV_MAIN} ~ {AI} + {IT_ORG} + {DMI} + {INVEST_CONTROL} + {AI}:{IT_ORG} + {AI}:{DMI}{CONTROL_SUFFIX}", f"{AI}:{DMI}", "Integrated H3|ai_use_sum:dmi", "가중치 적용 통합모형 H3 항"),
]

weighted_rows_before = len(RESULT_ROWS)
if WEIGHT not in analysis_df.columns:
    warnings.warn("weight 변수가 없어 Weighted OLS를 건너뜁니다.")
else:
    for model_name, hypothesis, dv, formula, term, ref_key, note in WEIGHTED_SPECS:
        required = sorted(set([dv, AI, IT_ORG, DMI, INVEST_CONTROL, WEIGHT] + available_controls))
        model, model_data, status = fit_wls_hc3(formula, analysis_df[[var for var in required if var in analysis_df.columns]], WEIGHT)
        add_fit(model_name, "Weighted OLS", "WLS", model, model_data, status)
        if model is not None:
            FULL_SUMMARIES.append(full_summary_text(model_name, "WLS HC3", formula, model))
            add_result("Weighted OLS", hypothesis, model_name, dv, term, model, model_data, "WLS", note, ref_key)
        else:
            warnings.warn(f"{model_name} 추정 실패: {status}")

weighted_ols_table = pd.DataFrame(RESULT_ROWS[weighted_rows_before:])
for col in ["계수", "표준오차", "p-value"]:
    if col in weighted_ols_table:
        weighted_ols_table[col] = weighted_ols_table[col].round(4)
display(weighted_ols_table)
TABLES["weighted_ols"] = weighted_ols_table

,가설,분석 구분,모형명,종속변수,핵심 계수,계수,표준오차,p-value,유의수준,N,적합도,방향,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론,비고
0,H1,Weighted OLS,H1 Weighted OLS,effect_proc_improve,ai_use_sum,0.0560,0.0084,0.0000,***,12203,"R² = 0.087, Adj. R² = 0.085",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 H1
1,H2 Headline,Weighted OLS,H2 Headline Weighted OLS,effect_proc_improve,ai_use_sum:it_org_any,0.0547,0.0154,0.0004,***,12203,"R² = 0.109, Adj. R² = 0.107",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 H2 headline
2,H3,Weighted OLS,H3 Weighted OLS,effect_proc_improve,ai_use_sum:dmi,0.0008,0.0016,0.6230,,12203,"R² = 0.104, Adj. R² = 0.102",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 H3
3,Integrated H2,Weighted OLS,Integrated Weighted OLS H2,effect_proc_improve,ai_use_sum:it_org_any,0.0517,0.0160,0.0012,**,12203,"R² = 0.115, Adj. R² = 0.113",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 통합모형 H2 항
4,Integrated H3,Weighted OLS,Integrated Weighted OLS H3,effect_proc_improve,ai_use_sum:dmi,-0.0003,0.0016,0.8425,,12203,"R² = 0.115, Adj. R² = 0.113",-,일치,일치,주모형과 방향·유의성 일치,가중치 적용 통합모형 H3 항

## 9. Robustness D: H4 Low DMI 하위집단 분석

In [28]:
low_dmi_rows_before = len(RESULT_ROWS)
dmi_group_rule = "생성되지 않음"
if DMI not in analysis_df.columns:
    warnings.warn("dmi 변수가 없어 Low DMI 분석을 건너뜁니다.")
else:
    dmi_values = analysis_df[DMI]
    try:
        dmi_group, dmi_bins = pd.qcut(dmi_values, q=3, labels=["Low", "Mid", "High"], retbins=True, duplicates="raise")
        analysis_df["dmi_group"] = pd.Categorical(dmi_group, categories=["Low", "Mid", "High"], ordered=True)
        dmi_group_rule = f"tertile 기준값: {np.round(dmi_bins, 3).tolist()}"
    except ValueError:
        median_value = dmi_values.median()
        analysis_df["dmi_group"] = pd.Categorical(np.where(dmi_values <= median_value, "Low", "High"), categories=["Low", "High"], ordered=True)
        dmi_group_rule = f"qcut 실패로 median 기준 Low/High 생성: median={median_value:.3f}"
    print("Low DMI 기준:", dmi_group_rule)
    display(analysis_df["dmi_group"].value_counts(dropna=False).sort_index().rename_axis("dmi_group").reset_index(name="N"))

    low_df = analysis_df[analysis_df["dmi_group"].astype(str) == "Low"].copy()
    low_specs = [
        ("H4 Low DMI OLS", "H4 Exploratory", f"{DV_MAIN} ~ {AI}{CONTROL_SUFFIX}", AI, "H4 Exploratory|ai_use_sum", "Low DMI 집단 AI 활용 범위 단독 관련성"),
        ("H4 Low DMI OLS with investment", "H4 Exploratory", f"{DV_MAIN} ~ {AI} + {INVEST_CONTROL}{CONTROL_SUFFIX}", AI, "H4 Exploratory|ai_use_sum", "Low DMI 집단 투자 통제 포함"),
    ]
    for model_name, hypothesis, formula, term, ref_key, note in low_specs:
        required = sorted(set([DV_MAIN, AI, INVEST_CONTROL] + available_controls))
        model, model_data, status = fit_ols_hc3(formula, low_df[[var for var in required if var in low_df.columns]])
        add_fit(model_name, "Low DMI Subsample", "Subsample OLS", model, model_data, status)
        if model is not None:
            FULL_SUMMARIES.append(full_summary_text(model_name, "Low DMI Subsample OLS HC3", formula, model))
            add_result("Low DMI Subsample", hypothesis, model_name, DV_MAIN, term, model, model_data, "Subsample OLS", note, ref_key)
        else:
            warnings.warn(f"{model_name} 추정 실패: {status}")

low_dmi_subsample_table = pd.DataFrame(RESULT_ROWS[low_dmi_rows_before:])
for col in ["계수", "표준오차", "p-value"]:
    if col in low_dmi_subsample_table:
        low_dmi_subsample_table[col] = low_dmi_subsample_table[col].round(4)
display(low_dmi_subsample_table)
TABLES["low_dmi_subsample"] = low_dmi_subsample_table

Low DMI 기준: tertile 기준값: [0.0, 4.0, 7.0, 29.0]

  dmi_group     N
0       Low  5238
1       Mid  3419
2      High  3546

,가설,분석 구분,모형명,종속변수,핵심 계수,계수,표준오차,p-value,유의수준,N,적합도,방향,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론,비고
0,H4 Exploratory,Low DMI Subsample,H4 Low DMI OLS,effect_proc_improve,ai_use_sum,-0.0082,0.0146,0.5765,,5238,"R² = 0.082, Adj. R² = 0.076",-,기준 없음,기준 없음,탐색적 결과,Low DMI 집단 AI 활용 범위 단독 관련성
1,H4 Exploratory,Low DMI Subsample,H4 Low DMI OLS with investment,effect_proc_improve,ai_use_sum,-0.0176,0.0145,0.2242,,5238,"R² = 0.087, Adj. R² = 0.081",-,기준 없음,기준 없음,탐색적 결과,Low DMI 집단 투자 통제 포함

## 10. Robustness E: AI 측정 대체

In [29]:
alt_ai_rows_before = len(RESULT_ROWS)
if AI_BINARY not in analysis_df.columns:
    warnings.warn("ai_use 변수가 없어 AI 측정 대체 분석을 건너뜁니다.")
else:
    alt_ai_formula = f"{DV_MAIN} ~ {AI_BINARY} + {IT_ORG} + {INVEST_CONTROL} + {AI_BINARY}:{IT_ORG}{CONTROL_SUFFIX}"
    required = sorted(set([DV_MAIN, AI_BINARY, IT_ORG, INVEST_CONTROL] + available_controls))
    model, model_data, status = fit_ols_hc3(alt_ai_formula, analysis_df[[var for var in required if var in analysis_df.columns]])
    add_fit("AI Measure Alternative OLS", "Alternative AI Measure", "OLS", model, model_data, status)
    if model is not None:
        FULL_SUMMARIES.append(full_summary_text("AI Measure Alternative OLS", "OLS HC3", alt_ai_formula, model))
        add_result("Alternative AI Measure", "AI Measure Alternative", "AI Measure Alternative OLS", DV_MAIN, f"{AI_BINARY}:{IT_ORG}", model, model_data, "OLS", "AI 이용 여부 × IT 조직 보유 보조 확인", "H2 Headline|ai_use_sum:it_org_any")
    else:
        warnings.warn(f"AI 측정 대체 분석 추정 실패: {status}")

alternative_ai_measure_table = pd.DataFrame(RESULT_ROWS[alt_ai_rows_before:])
for col in ["계수", "표준오차", "p-value"]:
    if col in alternative_ai_measure_table:
        alternative_ai_measure_table[col] = alternative_ai_measure_table[col].round(4)
display(alternative_ai_measure_table)
TABLES["alternative_ai_measure"] = alternative_ai_measure_table

,가설,분석 구분,모형명,종속변수,핵심 계수,계수,표준오차,p-value,유의수준,N,적합도,방향,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론,비고
0,AI Measure Alternative,Alternative AI Measure,AI Measure Alternative OLS,effect_proc_improve,ai_use:it_org_any,0.1561,0.0275,0.0,***,12203,"R² = 0.148, Adj. R² = 0.146",+,일치,일치,주모형과 방향·유의성 일치,AI 이용 여부 × IT 조직 보유 보조 확인

## 11. Full summary 확인

부록에 Python 결과 출력을 넣기 위해, 기준 주모형과 대안모형/강건성 모형의 full summary를 순서대로 출력한다. Ordered Logit처럼 수렴 실패가 발생한 모형은 fit stats 표의 상태 메시지로 확인한다.

In [30]:
print("=" * 120)
print("Main OLS reference model summaries")
print("=" * 120)

if MAIN_FULL_SUMMARIES:
    for summary_text in MAIN_FULL_SUMMARIES:
        print("\n" + summary_text)
else:
    print("출력할 주모형 기준 full summary가 없습니다. fit stats의 상태 메시지를 확인하세요.")

print("\n" + "=" * 120)
print("Alternative / robustness model summaries")
print("=" * 120)

if FULL_SUMMARIES:
    for summary_text in FULL_SUMMARIES:
        print("\n" + summary_text)
else:
    print("출력할 대안모형/강건성 full summary가 없습니다. fit stats의 상태 메시지를 확인하세요.")

========================================================================================================================
Main OLS reference model summaries
========================================================================================================================

====================================================================================================
H1 Main OLS
Estimator: OLS HC3
Formula: effect_proc_improve ~ ai_use_sum + firm_size + C(industry) + C(region) + C(firm_type)
====================================================================================================
                             OLS Regression Results
===============================================================================
Dep. Variable:     effect_proc_improve   R-squared:                       0.112
Model:                             OLS   Adj. R-squared:                  0.110
Method:                  Least Squares   F-statistic:                     48.95
Date:                 Mon, 11 May 2026   Prob (F-statistic):          6.41e-307
Time:                         05:12:39   Log-Likelihood:                -13306.
No. Observations:                12203   AIC:                         2.668e+04
Df Residuals:                    12168   BIC:                         2.694e+04
Df Model:                           34
Covariance Type:                   HC3
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             3.7547      0.043     87.521      0.000       3.671       3.839
C(industry)[T.2]     -0.0235      0.037     -0.637      0.524      -0.096       0.049
C(industry)[T.3]     -0.0420      0.063     -0.671      0.502      -0.165       0.081
C(industry)[T.4]     -0.0518      0.040     -1.296      0.195      -0.130       0.027
C(industry)[T.5]      0.0214      0.041      0.520      0.603      -0.059       0.102
C(industry)[T.6]      0.1532      0.042      3.650      0.000       0.071       0.236
C(industry)[T.7]     -0.0241      0.053     -0.453      0.650      -0.128       0.080
C(industry)[T.8]      0.3632      0.044      8.338      0.000       0.278       0.449
C(industry)[T.9]      0.1336      0.054      2.483      0.013       0.028       0.239
C(industry)[T.10]    -0.2596      0.052     -4.988      0.000      -0.362      -0.158
C(industry)[T.11]     0.1387      0.041      3.400      0.001       0.059       0.219
C(industry)[T.12]    -0.2426      0.044     -5.536      0.000      -0.328      -0.157
C(industry)[T.13]     0.1679      0.064      2.635      0.008       0.043       0.293
C(industry)[T.14]     0.1963      0.045      4.330      0.000       0.107       0.285
C(industry)[T.15]     0.1802      0.045      4.009      0.000       0.092       0.268
C(industry)[T.16]     0.0238      0.059      0.401      0.688      -0.093       0.140
C(region)[T.2]       -0.0981      0.030     -3.290      0.001      -0.157      -0.040
C(region)[T.3]       -0.1854      0.038     -4.829      0.000      -0.261      -0.110
C(region)[T.4]       -0.2847      0.035     -8.213      0.000      -0.353      -0.217
C(region)[T.5]       -0.4630      0.050     -9.236      0.000      -0.561      -0.365
C(region)[T.6]       -0.1443      0.046     -3.148      0.002      -0.234      -0.054
C(region)[T.7]       -0.1780      0.045     -3.916      0.000      -0.267      -0.089
C(region)[T.8]        0.2144      0.085      2.522      0.012       0.048       0.381
C(region)[T.9]       -0.1915      0.019     -9.967      0.000      -0.229      -0.154
C(region)[T.10]      -0.1156      0.053     -2.190      0.029      -0.219      -0.012
C(region)[T.11]      -0.0572      0.033     -1.735      0.083      -0.122       0.007
C(region)[T.12]      -0.1648      0.038     -4.393      0.000      -0.238      -0.091
C(region)[T.13]      -0.5351      0.047    -11.507      0.000      -0.626      -0.444
C(region)[T.14]      -0.4708      0.039    -11.930      0.000      -0.548      -0.393
C(region)[T.15]      -0.1255      0.033     -3.788      0.000      -0.190      -0.061
C(region)[T.16]      -0.1680      0.031     -5.484      0.000      -0.228      -0.108
C(region)[T.17]      -0.0236      0.061     -0.389      0.697      -0.142       0.095
C(firm_type)[T.2]     0.0891      0.025      3.580      0.000       0.040       0.138
ai_use_sum            0.0521      0.006      9.295      0.000       0.041       0.063
firm_size             0.1161      0.008     14.034      0.000       0.100       0.132
==============================================================================
Omnibus:                      260.762   Durbin-Watson:                   1.756
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              277.220
Skew:                          -0.365   Prob(JB):                     6.34e-61
Kurtosis:                       3.106   Cond. No.                         57.7
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

====================================================================================================
H2 Headline Main OLS
Estimator: OLS HC3
Formula: effect_proc_improve ~ ai_use_sum + it_org_any + it_invest_sum + ai_use_sum:it_org_any + firm_size + C(industry) + C(region) + C(firm_type)
====================================================================================================
                             OLS Regression Results
===============================================================================
Dep. Variable:     effect_proc_improve   R-squared:                       0.148
Model:                             OLS   Adj. R-squared:                  0.145
Method:                  Least Squares   F-statistic:                     62.61
Date:                 Mon, 11 May 2026   Prob (F-statistic):               0.00
Time:                         05:12:39   Log-Likelihood:                -13057.
No. Observations:                12203   AIC:                         2.619e+04
Df Residuals:                    12165   BIC:                         2.647e+04
Df Model:                           37
Covariance Type:                   HC3
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 3.5926      0.044     82.517      0.000       3.507       3.678
C(industry)[T.2]         -0.0510      0.036     -1.399      0.162      -0.122       0.020
C(industry)[T.3]         -0.0408      0.061     -0.672      0.502      -0.160       0.078
C(industry)[T.4]         -0.0494      0.039     -1.259      0.208      -0.126       0.028
C(industry)[T.5]         -0.0116      0.041     -0.287      0.774      -0.091       0.068
C(industry)[T.6]          0.2002      0.041      4.829      0.000       0.119       0.281
C(industry)[T.7]         -0.0163      0.052     -0.312      0.755      -0.119       0.086
C(industry)[T.8]          0.2418      0.043      5.597      0.000       0.157       0.326
C(industry)[T.9]          0.0573      0.053      1.082      0.279      -0.046       0.161
C(industry)[T.10]        -0.1929      0.051     -3.788      0.000      -0.293      -0.093
C(industry)[T.11]         0.1015      0.040      2.524      0.012       0.023       0.180
C(industry)[T.12]        -0.1858      0.043     -4.318      0.000      -0.270      -0.101
C(industry)[T.13]         0.1141      0.062      1.855      0.064      -0.006       0.235
C(industry)[T.14]         0.1695      0.045      3.792      0.000       0.082       0.257
C(industry)[T.15]         0.1628      0.045      3.612      0.000       0.074       0.251
C(industry)[T.16]         0.0478      0.058      0.818      0.413      -0.067       0.162
C(region)[T.2]           -0.1591      0.030     -5.368      0.000      -0.217      -0.101
C(region)[T.3]           -0.2527      0.038     -6.689      0.000      -0.327      -0.179
C(region)[T.4]           -0.2438      0.034     -7.184      0.000      -0.310      -0.177
C(region)[T.5]           -0.3922      0.049     -7.925      0.000      -0.489      -0.295
C(region)[T.6]           -0.1826      0.046     -3.957      0.000      -0.273      -0.092
C(region)[T.7]           -0.2437      0.045     -5.467      0.000      -0.331      -0.156
C(region)[T.8]            0.2065      0.093      2.230      0.026       0.025       0.388
C(region)[T.9]           -0.1545      0.019     -8.219      0.000      -0.191      -0.118
C(region)[T.10]          -0.0960      0.051     -1.872      0.061      -0.196       0.005
C(region)[T.11]          -0.1079      0.034     -3.174      0.002      -0.175      -0.041
C(region)[T.12]          -0.1722      0.038     -4.588      0.000      -0.246      -0.099
C(region)[T.13]          -0.4563      0.046     -9.883      0.000      -0.547      -0.366
C(region)[T.14]          -0.4504      0.039    -11.464      0.000      -0.527      -0.373
C(region)[T.15]          -0.1952      0.033     -5.921      0.000      -0.260      -0.131
C(region)[T.16]          -0.2389      0.030     -7.865      0.000      -0.298      -0.179
C(region)[T.17]           0.0438      0.061      0.723      0.470      -0.075       0.162
C(firm_type)[T.2]         0.0626      0.025      2.539      0.011       0.014       0.111
ai_use_sum               -0.0237      0.009     -2.632      0.008      -0.041      -0.006
it_org_any                0.0110      0.017      0.632      0.527      -0.023       0.045
it_invest_sum             0.1081      0.006     18.606      0.000       0.097       0.119
ai_use_sum:it_org_any     0.0575      0.011      5.382      0.000       0.037       0.078
firm_size                 0.0522      0.009      5.980      0.000       0.035       0.069
==============================================================================
Omnibus:                      216.429   Durbin-Watson:                   1.752
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              227.688
Skew:                          -0.331   Prob(JB):                     3.62e-50
Kurtosis:                       3.102   Cond. No.                         96.7
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

====================================================================================================
H3 Main OLS
Estimator: OLS HC3
Formula: effect_proc_improve ~ ai_use_sum + dmi + ai_use_sum:dmi + firm_size + C(industry) + C(region) + C(firm_type)
====================================================================================================
                             OLS Regression Results
===============================================================================
Dep. Variable:     effect_proc_improve   R-squared:                       0.126
Model:                             OLS   Adj. R-squared:                  0.124
Method:                  Least Squares   F-statistic:                     53.43
Date:                 Mon, 11 May 2026   Prob (F-statistic):               0.00
Time:                         05:12:39   Log-Likelihood:                -13210.
No. Observations:                12203   AIC:                         2.649e+04
Df Residuals:                    12166   BIC:                         2.677e+04
Df Model:                           36
Covariance Type:                   HC3
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             3.7086      0.043     85.889      0.000       3.624       3.793
C(industry)[T.2]     -0.0355      0.037     -0.965      0.335      -0.108       0.037
C(industry)[T.3]     -0.0360      0.062     -0.578      0.563      -0.158       0.086
C(industry)[T.4]     -0.0545      0.040     -1.372      0.170      -0.132       0.023
C(industry)[T.5]     -0.0319      0.041     -0.773      0.440      -0.113       0.049
C(industry)[T.6]      0.1501      0.042      3.607      0.000       0.069       0.232
C(industry)[T.7]     -0.0512      0.053     -0.970      0.332      -0.155       0.052
C(industry)[T.8]      0.3159      0.043      7.286      0.000       0.231       0.401
C(industry)[T.9]      0.1003      0.054      1.870      0.061      -0.005       0.205
C(industry)[T.10]    -0.2076      0.051     -4.043      0.000      -0.308      -0.107
C(industry)[T.11]     0.1208      0.041      2.970      0.003       0.041       0.200
C(industry)[T.12]    -0.2247      0.044     -5.136      0.000      -0.310      -0.139
C(industry)[T.13]     0.1278      0.064      2.003      0.045       0.003       0.253
C(industry)[T.14]     0.1433      0.045      3.178      0.001       0.055       0.232
C(industry)[T.15]     0.1484      0.045      3.298      0.001       0.060       0.237
C(industry)[T.16]     0.0067      0.059      0.113      0.910      -0.108       0.122
C(region)[T.2]       -0.1205      0.029     -4.127      0.000      -0.178      -0.063
C(region)[T.3]       -0.2250      0.038     -5.941      0.000      -0.299      -0.151
C(region)[T.4]       -0.2624      0.035     -7.482      0.000      -0.331      -0.194
C(region)[T.5]       -0.4332      0.049     -8.815      0.000      -0.529      -0.337
C(region)[T.6]       -0.1066      0.046     -2.298      0.022      -0.197      -0.016
C(region)[T.7]       -0.1880      0.045     -4.185      0.000      -0.276      -0.100
C(region)[T.8]        0.2570      0.084      3.078      0.002       0.093       0.421
C(region)[T.9]       -0.1743      0.019     -9.114      0.000      -0.212      -0.137
C(region)[T.10]      -0.1045      0.054     -1.951      0.051      -0.209       0.000
C(region)[T.11]      -0.0101      0.033     -0.303      0.762      -0.076       0.055
C(region)[T.12]      -0.1394      0.038     -3.682      0.000      -0.214      -0.065
C(region)[T.13]      -0.4930      0.046    -10.765      0.000      -0.583      -0.403
C(region)[T.14]      -0.4504      0.039    -11.595      0.000      -0.526      -0.374
C(region)[T.15]      -0.1428      0.033     -4.370      0.000      -0.207      -0.079
C(region)[T.16]      -0.1789      0.030     -5.999      0.000      -0.237      -0.120
C(region)[T.17]       0.0302      0.059      0.509      0.611      -0.086       0.147
C(firm_type)[T.2]     0.0752      0.025      3.038      0.002       0.027       0.124
ai_use_sum            0.0020      0.010      0.209      0.835      -0.017       0.021
dmi                   0.0276      0.002     12.001      0.000       0.023       0.032
ai_use_sum:dmi        0.0004      0.001      0.491      0.623      -0.001       0.002
firm_size             0.0852      0.009      9.955      0.000       0.068       0.102
==============================================================================
Omnibus:                      264.152   Durbin-Watson:                   1.765
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              281.150
Skew:                          -0.366   Prob(JB):                     8.89e-62
Kurtosis:                       3.131   Cond. No.                         428.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

====================================================================================================
Integrated Main OLS H2
Estimator: OLS HC3
Formula: effect_proc_improve ~ ai_use_sum + it_org_any + dmi + it_invest_sum + ai_use_sum:it_org_any + ai_use_sum:dmi + firm_size + C(industry) + C(region) + C(firm_type)
====================================================================================================
                             OLS Regression Results
===============================================================================
Dep. Variable:     effect_proc_improve   R-squared:                       0.151
Model:                             OLS   Adj. R-squared:                  0.148
Method:                  Least Squares   F-statistic:                     61.41
Date:                 Mon, 11 May 2026   Prob (F-statistic):               0.00
Time:                         05:12:39   Log-Likelihood:                -13037.
No. Observations:                12203   AIC:                         2.615e+04
Df Residuals:                    12163   BIC:                         2.645e+04
Df Model:                           39
Covariance Type:                   HC3
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 3.5862      0.044     82.141      0.000       3.501       3.672
C(industry)[T.2]         -0.0550      0.036     -1.512      0.130      -0.126       0.016
C(industry)[T.3]         -0.0380      0.061     -0.625      0.532      -0.157       0.081
C(industry)[T.4]         -0.0501      0.039     -1.277      0.202      -0.127       0.027
C(industry)[T.5]         -0.0354      0.041     -0.868      0.385      -0.115       0.044
C(industry)[T.6]          0.1932      0.041      4.667      0.000       0.112       0.274
C(industry)[T.7]         -0.0318      0.052     -0.608      0.543      -0.134       0.071
C(industry)[T.8]          0.2312      0.043      5.362      0.000       0.147       0.316
C(industry)[T.9]          0.0469      0.053      0.886      0.375      -0.057       0.151
C(industry)[T.10]        -0.1771      0.051     -3.495      0.000      -0.276      -0.078
C(industry)[T.11]         0.0955      0.040      2.372      0.018       0.017       0.174
C(industry)[T.12]        -0.1846      0.043     -4.287      0.000      -0.269      -0.100
C(industry)[T.13]         0.0973      0.062      1.573      0.116      -0.024       0.218
C(industry)[T.14]         0.1437      0.045      3.209      0.001       0.056       0.231
C(industry)[T.15]         0.1485      0.045      3.290      0.001       0.060       0.237
C(industry)[T.16]         0.0360      0.058      0.619      0.536      -0.078       0.150
C(region)[T.2]           -0.1635      0.029     -5.557      0.000      -0.221      -0.106
C(region)[T.3]           -0.2650      0.038     -7.041      0.000      -0.339      -0.191
C(region)[T.4]           -0.2366      0.034     -6.926      0.000      -0.304      -0.170
C(region)[T.5]           -0.3853      0.049     -7.838      0.000      -0.482      -0.289
C(region)[T.6]           -0.1570      0.046     -3.380      0.001      -0.248      -0.066
C(region)[T.7]           -0.2401      0.045     -5.394      0.000      -0.327      -0.153
C(region)[T.8]            0.2282      0.091      2.518      0.012       0.051       0.406
C(region)[T.9]           -0.1507      0.019     -8.013      0.000      -0.188      -0.114
C(region)[T.10]          -0.0942      0.052     -1.821      0.069      -0.196       0.007
C(region)[T.11]          -0.0760      0.034     -2.210      0.027      -0.143      -0.009
C(region)[T.12]          -0.1575      0.038     -4.162      0.000      -0.232      -0.083
C(region)[T.13]          -0.4458      0.046     -9.708      0.000      -0.536      -0.356
C(region)[T.14]          -0.4400      0.039    -11.233      0.000      -0.517      -0.363
C(region)[T.15]          -0.1948      0.033     -5.934      0.000      -0.259      -0.130
C(region)[T.16]          -0.2353      0.030     -7.821      0.000      -0.294      -0.176

## 12. 전체 대안모형/강건성 결과표

In [31]:
alternative_robustness_results_long = pd.concat([main_reference_table, pd.DataFrame(RESULT_ROWS)], ignore_index=True)
for col in ["계수", "표준오차", "p-value"]:
    alternative_robustness_results_long[col] = pd.to_numeric(alternative_robustness_results_long[col], errors="coerce").round(4)

display(alternative_robustness_results_long)
TABLES["long_results"] = alternative_robustness_results_long

alternative_robustness_results_wide = alternative_robustness_results_long.copy()
alternative_robustness_results_wide["계수(SE)"] = alternative_robustness_results_wide.apply(
    lambda row: format_coef_with_stars(row["계수"], row["표준오차"], row["p-value"]), axis=1
)
display(alternative_robustness_results_wide[["가설", "분석 구분", "모형명", "종속변수", "핵심 계수", "계수(SE)", "N", "적합도", "주모형 방향과 일치 여부", "주모형 유의성과 일치 여부", "결론"]])
TABLES["wide_results"] = alternative_robustness_results_wide

alternative_robustness_fit_stats = pd.DataFrame(FIT_ROWS)
for col in ["AIC", "BIC", "R²", "Adj. R²"]:
    if col in alternative_robustness_fit_stats:
        alternative_robustness_fit_stats[col] = pd.to_numeric(alternative_robustness_fit_stats[col], errors="coerce").round(4)
display(alternative_robustness_fit_stats)
TABLES["fit_stats"] = alternative_robustness_fit_stats

,가설,분석 구분,모형명,종속변수,핵심 계수,계수,표준오차,p-value,유의수준,N,적합도,방향,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론,비고
0,H1,Main OLS 기준,H1 Main OLS,effect_proc_improve,ai_use_sum,0.0521,0.0056,0.0000,***,12203,"R² = 0.112, Adj. R² = 0.110",+,기준,기준,주모형 기준,비교 기준값
1,H2 Headline,Main OLS 기준,H2 Headline Main OLS,effect_proc_improve,ai_use_sum:it_org_any,0.0575,0.0107,0.0000,***,12203,"R² = 0.148, Adj. R² = 0.145",+,기준,기준,주모형 기준,비교 기준값
2,H3,Main OLS 기준,H3 Main OLS,effect_proc_improve,ai_use_sum:dmi,0.0004,0.0007,0.6233,,12203,"R² = 0.126, Adj. R² = 0.124",+,기준,기준,주모형 기준,비교 기준값
3,Integrated H2,Main OLS 기준,Integrated Main OLS H2,effect_proc_improve,ai_use_sum:it_org_any,0.0601,0.0119,0.0000,***,12203,"R² = 0.151, Adj. R² = 0.148",+,기준,기준,주모형 기준,비교 기준값
4,Integrated H3,Main OLS 기준,Integrated Main OLS H3,effect_proc_improve,ai_use_sum:dmi,-0.0015,0.0008,0.0661,,12203,"R² = 0.151, Adj. R² = 0.148",-,기준,기준,주모형 기준,비교 기준값
5,H1,Ordered Logit,H1 Ordered Logit,effect_proc_improve,ai_use_sum,0.1471,0.0152,0.0000,***,12203,"Log-likelihood = -12984.5, AIC = 26044.9, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,순서형 DV 대안모형
6,H2 Headline,Ordered Logit,H2 Headline Ordered Logit,effect_proc_improve,ai_use_sum:it_org_any,0.1933,0.0294,0.0000,***,12203,"Log-likelihood = -12728.8, AIC = 25539.5, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,H2 headline의 Ordered Logit 확인
7,H3,Ordered Logit,H3 Ordered Logit,effect_proc_improve,ai_use_sum:dmi,0.0047,0.0026,0.0632,,12203,"Log-likelihood = -12872.7, AIC = 25825.3, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,H3 Ordered Logit 확인
8,Integrated H2,Ordered Logit,Integrated Ordered Logit H2,effect_proc_improve,ai_use_sum:it_org_any,0.1851,0.0316,0.0000,***,12203,"Log-likelihood = -12705.4, AIC = 25496.8, BIC ...",+,일치,일치,주모형과 방향·유의성 일치,통합 Ordered Logit의 H2 항
9,Integrated H3,Ordered Logit,Integrated Ordered Logit H3,effect_proc_improve,ai_use_sum:dmi,-0.0014,0.0027,0.5947,,12203,"Log-likelihood = -12705.4, AIC = 25496.8, BIC ...",-,일치,일치,주모형과 방향·유의성 일치,통합 Ordered Logit의 H3 항
10,H1,Alternative DV OLS,H1 Alternative DV OLS,effect_average,ai_use_sum,0.0557,0.0045,0.0000,***,12203,"R² = 0.199, Adj. R² = 0.196",+,일치,일치,주모형과 방향·유의성 일치,대체 DV에서 H1 방향 확인
11,H2 Headline,Alternative DV OLS,H2 Headline Alternative DV OLS,effect_average,ai_use_sum:it_org_any,0.0739,0.0081,0.0000,***,12203,"R² = 0.265, Adj. R² = 0.263",+,일치,일치,주모형과 방향·유의성 일치,대체 DV에서 H2 headline 확인
12,H3,Alternative DV OLS,H3 Alternative DV OLS,effect_average,ai_use_sum:dmi,0.0015,0.0006,0.0072,**,12203,"R² = 0.245, Adj. R² = 0.243",+,일치,불일치,방향은 일치하나 유의성은 약함,대체 DV에서 H3 확인
13,Integrated H2,Alternative DV OLS,Integrated Alternative DV OLS H2,effect_average,ai_use_sum:it_org_any,0.0676,0.0090,0.0000,***,12203,"R² = 0.282, Adj. R² = 0.280",+,일치,일치,주모형과 방향·유의성 일치,대체 DV 통합모형 H2 항
14,Integrated H3,Alternative DV OLS,Integrated Alternative DV OLS H3,effect_average,ai_use_sum:dmi,-0.0006,0.0006,0.3523,,12203,"R² = 0.282, Adj. R² = 0.280",-,일치,일치,주모형과 방향·유의성 일치,대체 DV 통합모형 H3 항
15,H1,Weighted OLS,H1 Weighted OLS,effect_proc_improve,ai_use_sum,0.0560,0.0084,0.0000,***,12203,"R² = 0.087, Adj. R² = 0.085",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 H1
16,H2 Headline,Weighted OLS,H2 Headline Weighted OLS,effect_proc_improve,ai_use_sum:it_org_any,0.0547,0.0154,0.0004,***,12203,"R² = 0.109, Adj. R² = 0.107",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 H2 headline
17,H3,Weighted OLS,H3 Weighted OLS,effect_proc_improve,ai_use_sum:dmi,0.0008,0.0016,0.6230,,12203,"R² = 0.104, Adj. R² = 0.102",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 H3
18,Integrated H2,Weighted OLS,Integrated Weighted OLS H2,effect_proc_improve,ai_use_sum:it_org_any,0.0517,0.0160,0.0012,**,12203,"R² = 0.115, Adj. R² = 0.113",+,일치,일치,주모형과 방향·유의성 일치,가중치 적용 통합모형 H2 항
19,Integrated H3,Weighted OLS,Integrated Weighted OLS H3,effect_proc_improve,ai_use_sum:dmi,-0.0003,0.0016,0.8425,,12203,"R² = 0.115, Adj. R² = 0.113",-,일치,일치,주모형과 방향·유의성 일치,가중치 적용 통합모형 H3 항
20,H4 Exploratory,Low DMI Subsample,H4 Low DMI OLS,effect_proc_improve,ai_use_sum,-0.0082,0.0146,0.5765,,5238,"R² = 0.082, Adj. R² = 0.076",-,기준 없음,기준 없음,탐색적 결과,Low DMI 집단 AI 활용 범위 단독 관련성
21,H4 Exploratory,Low DMI Subsample,H4 Low DMI OLS with investment,effect_proc_improve,ai_use_sum,-0.0176,0.0145,0.2242,,5238,"R² = 0.087, Adj. R² = 0.081",-,기준 없음,기준 없음,탐색적 결과,Low DMI 집단 투자 통제 포함
22,AI Measure Alternative,Alternative AI Measure,AI Measure Alternative OLS,effect_proc_improve,ai_use:it_org_any,0.1561,0.0275,0.0000,***,12203,"R² = 0.148, Adj. R² = 0.146",+,일치,일치,주모형과 방향·유의성 일치,AI 이용 여부 × IT 조직 보유 보조 확인

,가설,분석 구분,모형명,종속변수,핵심 계수,계수(SE),N,적합도,주모형 방향과 일치 여부,주모형 유의성과 일치 여부,결론
0,H1,Main OLS 기준,H1 Main OLS,effect_proc_improve,ai_use_sum,0.052***\n(0.006),12203,"R² = 0.112, Adj. R² = 0.110",기준,기준,주모형 기준
1,H2 Headline,Main OLS 기준,H2 Headline Main OLS,effect_proc_improve,ai_use_sum:it_org_any,0.058***\n(0.011),12203,"R² = 0.148, Adj. R² = 0.145",기준,기준,주모형 기준
2,H3,Main OLS 기준,H3 Main OLS,effect_proc_improve,ai_use_sum:dmi,0.000\n(0.001),12203,"R² = 0.126, Adj. R² = 0.124",기준,기준,주모형 기준
3,Integrated H2,Main OLS 기준,Integrated Main OLS H2,effect_proc_improve,ai_use_sum:it_org_any,0.060***\n(0.012),12203,"R² = 0.151, Adj. R² = 0.148",기준,기준,주모형 기준
4,Integrated H3,Main OLS 기준,Integrated Main OLS H3,effect_proc_improve,ai_use_sum:dmi,-0.002\n(0.001),12203,"R² = 0.151, Adj. R² = 0.148",기준,기준,주모형 기준
5,H1,Ordered Logit,H1 Ordered Logit,effect_proc_improve,ai_use_sum,0.147***\n(0.015),12203,"Log-likelihood = -12984.5, AIC = 26044.9, BIC ...",일치,일치,주모형과 방향·유의성 일치
6,H2 Headline,Ordered Logit,H2 Headline Ordered Logit,effect_proc_improve,ai_use_sum:it_org_any,0.193***\n(0.029),12203,"Log-likelihood = -12728.8, AIC = 25539.5, BIC ...",일치,일치,주모형과 방향·유의성 일치
7,H3,Ordered Logit,H3 Ordered Logit,effect_proc_improve,ai_use_sum:dmi,0.005\n(0.003),12203,"Log-likelihood = -12872.7, AIC = 25825.3, BIC ...",일치,일치,주모형과 방향·유의성 일치
8,Integrated H2,Ordered Logit,Integrated Ordered Logit H2,effect_proc_improve,ai_use_sum:it_org_any,0.185***\n(0.032),12203,"Log-likelihood = -12705.4, AIC = 25496.8, BIC ...",일치,일치,주모형과 방향·유의성 일치
9,Integrated H3,Ordered Logit,Integrated Ordered Logit H3,effect_proc_improve,ai_use_sum:dmi,-0.001\n(0.003),12203,"Log-likelihood = -12705.4, AIC = 25496.8, BIC ...",일치,일치,주모형과 방향·유의성 일치
10,H1,Alternative DV OLS,H1 Alternative DV OLS,effect_average,ai_use_sum,0.056***\n(0.004),12203,"R² = 0.199, Adj. R² = 0.196",일치,일치,주모형과 방향·유의성 일치
11,H2 Headline,Alternative DV OLS,H2 Headline Alternative DV OLS,effect_average,ai_use_sum:it_org_any,0.074***\n(0.008),12203,"R² = 0.265, Adj. R² = 0.263",일치,일치,주모형과 방향·유의성 일치
12,H3,Alternative DV OLS,H3 Alternative DV OLS,effect_average,ai_use_sum:dmi,0.002**\n(0.001),12203,"R² = 0.245, Adj. R² = 0.243",일치,불일치,방향은 일치하나 유의성은 약함
13,Integrated H2,Alternative DV OLS,Integrated Alternative DV OLS H2,effect_average,ai_use_sum:it_org_any,0.068***\n(0.009),12203,"R² = 0.282, Adj. R² = 0.280",일치,일치,주모형과 방향·유의성 일치
14,Integrated H3,Alternative DV OLS,Integrated Alternative DV OLS H3,effect_average,ai_use_sum:dmi,-0.001\n(0.001),12203,"R² = 0.282, Adj. R² = 0.280",일치,일치,주모형과 방향·유의성 일치
15,H1,Weighted OLS,H1 Weighted OLS,effect_proc_improve,ai_use_sum,0.056***\n(0.008),12203,"R² = 0.087, Adj. R² = 0.085",일치,일치,주모형과 방향·유의성 일치
16,H2 Headline,Weighted OLS,H2 Headline Weighted OLS,effect_proc_improve,ai_use_sum:it_org_any,0.055***\n(0.015),12203,"R² = 0.109, Adj. R² = 0.107",일치,일치,주모형과 방향·유의성 일치
17,H3,Weighted OLS,H3 Weighted OLS,effect_proc_improve,ai_use_sum:dmi,0.001\n(0.002),12203,"R² = 0.104, Adj. R² = 0.102",일치,일치,주모형과 방향·유의성 일치
18,Integrated H2,Weighted OLS,Integrated Weighted OLS H2,effect_proc_improve,ai_use_sum:it_org_any,0.052**\n(0.016),12203,"R² = 0.115, Adj. R² = 0.113",일치,일치,주모형과 방향·유의성 일치
19,Integrated H3,Weighted OLS,Integrated Weighted OLS H3,effect_proc_improve,ai_use_sum:dmi,-0.000\n(0.002),12203,"R² = 0.115, Adj. R² = 0.113",일치,일치,주모형과 방향·유의성 일치
20,H4 Exploratory,Low DMI Subsample,H4 Low DMI OLS,effect_proc_improve,ai_use_sum,-0.008\n(0.015),5238,"R² = 0.082, Adj. R² = 0.076",기준 없음,기준 없음,탐색적 결과
21,H4 Exploratory,Low DMI Subsample,H4 Low DMI OLS with investment,effect_proc_improve,ai_use_sum,-0.018\n(0.015),5238,"R² = 0.087, Adj. R² = 0.081",기준 없음,기준 없음,탐색적 결과
22,AI Measure Alternative,Alternative AI Measure,AI Measure Alternative OLS,effect_proc_improve,ai_use:it_org_any,0.156***\n(0.028),12203,"R² = 0.148, Adj. R² = 0.146",일치,일치,주모형과 방향·유의성 일치

                     분석 구분                               모형명          모형 유형      N  상태                                                적합도         AIC         BIC      R²  Adj. R²
0              Main OLS 기준                       H1 Main OLS            OLS  12203  ok                        R² = 0.112, Adj. R² = 0.110  26682.8023  26942.1326  0.1125   0.1100
1              Main OLS 기준              H2 Headline Main OLS            OLS  12203  ok                        R² = 0.148, Adj. R² = 0.145  26190.1437  26471.7023  0.1480   0.1454
2              Main OLS 기준                       H3 Main OLS            OLS  12203  ok                        R² = 0.126, Adj. R² = 0.124  26493.1694  26767.3185  0.1265   0.1239
3              Main OLS 기준            Integrated Main OLS H2            OLS  12203  ok                        R² = 0.151, Adj. R² = 0.148  26153.7672  26450.1447  0.1508   0.1481
4              Main OLS 기준            Integrated Main OLS H3            OLS  12203  ok                        R² = 0.151, Adj. R² = 0.148  26153.7672  26450.1447  0.1508   0.1481
5            Ordered Logit                  H1 Ordered Logit  Ordered Logit  12203  ok  Log-likelihood = -12984.5, AIC = 26044.9, BIC ...  26044.9021  26326.4607     NaN      NaN
6            Ordered Logit         H2 Headline Ordered Logit  Ordered Logit  12203  ok  Log-likelihood = -12728.8, AIC = 25539.5, BIC ...  25539.5042  25843.2911     NaN      NaN
7            Ordered Logit                  H3 Ordered Logit  Ordered Logit  12203  ok  Log-likelihood = -12872.7, AIC = 25825.3, BIC ...  25825.3149  26121.6924     NaN      NaN
8            Ordered Logit       Integrated Ordered Logit H2  Ordered Logit  12203  ok  Log-likelihood = -12705.4, AIC = 25496.8, BIC ...  25496.7669  25815.3727     NaN      NaN
9            Ordered Logit       Integrated Ordered Logit H3  Ordered Logit  12203  ok  Log-likelihood = -12705.4, AIC = 25496.8, BIC ...  25496.7669  25815.3727     NaN      NaN
10      Alternative DV OLS             H1 Alternative DV OLS            OLS  12203  ok                        R² = 0.199, Adj. R² = 0.196  20010.0723  20269.4026  0.1986   0.1964
11      Alternative DV OLS    H2 Headline Alternative DV OLS            OLS  12203  ok                        R² = 0.265, Adj. R² = 0.263  18965.1171  19246.6757  0.2647   0.2625
12      Alternative DV OLS             H3 Alternative DV OLS            OLS  12203  ok                        R² = 0.245, Adj. R² = 0.243  19278.5835  19552.7327  0.2455   0.2433
13      Alternative DV OLS  Integrated Alternative DV OLS H2            OLS  12203  ok                        R² = 0.282, Adj. R² = 0.280  18681.7603  18978.1377  0.2819   0.2795
14      Alternative DV OLS  Integrated Alternative DV OLS H3            OLS  12203  ok                        R² = 0.282, Adj. R² = 0.280  18681.7603  18978.1377  0.2819   0.2795
15            Weighted OLS                   H1 Weighted OLS            WLS  12203  ok                        R² = 0.087, Adj. R² = 0.085  34524.3279  34783.6582  0.0872   0.0847
16            Weighted OLS          H2 Headline Weighted OLS            WLS  12203  ok                        R² = 0.109, Adj. R² = 0.107  34230.7068  34512.2654  0.1094   0.1067
17            Weighted OLS                   H3 Weighted OLS            WLS  12203  ok                        R² = 0.104, Adj. R² = 0.102  34298.2254  34572.3746  0.1043   0.1016
18            Weighted OLS        Integrated Weighted OLS H2            WLS  12203  ok                        R² = 0.115, Adj. R² = 0.113  34151.8317  34448.2092  0.1154   0.1126
19            Weighted OLS        Integrated Weighted OLS H3            WLS  12203  ok                        R² = 0.115, Adj. R² = 0.113  34151.8317  34448.2092  0.1154   0.1126
20       Low DMI Subsample                    H4 Low DMI OLS  Subsample OLS   5238  ok                        R² = 0.082, Adj. R² = 0.076  11400.3518  11630.0812  0.0823   0.0763
21       Low DMI Subsample    H4 Low DMI OLS with investment  Subsample OLS   5238  ok                        R² = 0.087, Adj. R² = 0.081  11374.4551  11610.7481  0.0872   0.0811
22  Alternative AI Measure        AI Measure Alternative OLS            OLS  12203  ok                        R² = 0.148, Adj. R² = 0.146  26188.5220  26470.0806  0.1481   0.1456

## 13. 보고서용 간결 비교표

In [32]:
report_rows = [
    ("H1", "Ordered Logit", "H1 Ordered Logit"),
    ("H2 Headline", "Ordered Logit", "H2 Headline Ordered Logit"),
    ("H3", "Ordered Logit", "H3 Ordered Logit"),
    ("H1", "Alternative DV", "H1 Alternative DV OLS"),
    ("H2 Headline", "Alternative DV", "H2 Headline Alternative DV OLS"),
    ("H3", "Alternative DV", "H3 Alternative DV OLS"),
    ("H2 Headline", "Weighted OLS", "H2 Headline Weighted OLS"),
    ("H3", "Weighted OLS", "H3 Weighted OLS"),
    ("H4 Exploratory", "Low DMI Subsample", "H4 Low DMI OLS"),
    ("AI Measure Alternative", "Alternative AI Measure", "AI Measure Alternative OLS"),
]
report_names = [name for _, _, name in report_rows]
report_table = alternative_robustness_results_long[alternative_robustness_results_long["모형명"].isin(report_names)].copy()
report_table["보조모형 구분"] = report_table["모형명"].map({name: group for _, group, name in report_rows})
report_table = report_table[[
    "가설", "보조모형 구분", "종속변수", "핵심 계수", "계수", "표준오차", "p-value", "N", "적합도", "결론",
]].rename(columns={"결론": "주모형 일치 여부"})
for col in ["계수", "표준오차", "p-value"]:
    report_table[col] = pd.to_numeric(report_table[col], errors="coerce").round(4)

display(report_table)
TABLES["report_table"] = report_table

                        가설                 보조모형 구분                 종속변수                  핵심 계수      계수    표준오차  p-value      N                                                적합도         주모형 일치 여부
5                       H1           Ordered Logit  effect_proc_improve             ai_use_sum  0.1471  0.0152   0.0000  12203  Log-likelihood = -12984.5, AIC = 26044.9, BIC ...    주모형과 방향·유의성 일치
6              H2 Headline           Ordered Logit  effect_proc_improve  ai_use_sum:it_org_any  0.1933  0.0294   0.0000  12203  Log-likelihood = -12728.8, AIC = 25539.5, BIC ...    주모형과 방향·유의성 일치
7                       H3           Ordered Logit  effect_proc_improve         ai_use_sum:dmi  0.0047  0.0026   0.0632  12203  Log-likelihood = -12872.7, AIC = 25825.3, BIC ...    주모형과 방향·유의성 일치
10                      H1          Alternative DV       effect_average             ai_use_sum  0.0557  0.0045   0.0000  12203                        R² = 0.199, Adj. R² = 0.196    주모형과 방향·유의성 일치
11             H2 Headline          Alternative DV       effect_average  ai_use_sum:it_org_any  0.0739  0.0081   0.0000  12203                        R² = 0.265, Adj. R² = 0.263    주모형과 방향·유의성 일치
12                      H3          Alternative DV       effect_average         ai_use_sum:dmi  0.0015  0.0006   0.0072  12203                        R² = 0.245, Adj. R² = 0.243  방향은 일치하나 유의성은 약함
16             H2 Headline            Weighted OLS  effect_proc_improve  ai_use_sum:it_org_any  0.0547  0.0154   0.0004  12203                        R² = 0.109, Adj. R² = 0.107    주모형과 방향·유의성 일치
17                      H3            Weighted OLS  effect_proc_improve         ai_use_sum:dmi  0.0008  0.0016   0.6230  12203                        R² = 0.104, Adj. R² = 0.102    주모형과 방향·유의성 일치
20          H4 Exploratory       Low DMI Subsample  effect_proc_improve             ai_use_sum -0.0082  0.0146   0.5765   5238                        R² = 0.082, Adj. R² = 0.076            탐색적 결과
22  AI Measure Alternative  Alternative AI Measure  effect_proc_improve      ai_use:it_org_any  0.1561  0.0275   0.0000  12203                        R² = 0.148, Adj. R² = 0.146    주모형과 방향·유의성 일치

## 14. 보고서용 해석 메모 초안

In [33]:
def find_row(hypothesis, analysis_group=None, model_name=None):
    data = alternative_robustness_results_long
    mask = data["가설"].eq(hypothesis)
    if analysis_group is not None:
        mask &= data["분석 구분"].eq(analysis_group)
    if model_name is not None:
        mask &= data["모형명"].eq(model_name)
    sub = data[mask]
    return None if sub.empty else sub.iloc[0]


def row_phrase(row):
    if row is None:
        return "확인 필요"
    sig = "유의성이 확인됨" if pd.notna(row["p-value"]) and row["p-value"] < 0.05 else "유의성은 뚜렷하지 않음"
    return f"{row['방향']} 방향, {sig}, {row['결론']}"

h1_ord = find_row("H1", "Ordered Logit")
h1_alt = find_row("H1", "Alternative DV OLS")
h2_ord = find_row("H2 Headline", "Ordered Logit")
h2_alt = find_row("H2 Headline", "Alternative DV OLS")
h2_w = find_row("H2 Headline", "Weighted OLS")
h3_ord = find_row("H3", "Ordered Logit")
h3_alt = find_row("H3", "Alternative DV OLS")
h3_w = find_row("H3", "Weighted OLS")
h4 = find_row("H4 Exploratory", "Low DMI Subsample", "H4 Low DMI OLS")
ai_alt = find_row("AI Measure Alternative", "Alternative AI Measure")

interpretation_lines = [
    f"H1은 Ordered Logit에서 {row_phrase(h1_ord)}, 대체 DV 모형에서 {row_phrase(h1_alt)}으로 나타났다.",
    f"H2 Headline의 `ai_use_sum:it_org_any` 항은 Ordered Logit에서 {row_phrase(h2_ord)}, 대체 DV에서 {row_phrase(h2_alt)}, weighted OLS에서 {row_phrase(h2_w)}으로 확인된다.",
    f"H3의 `ai_use_sum:dmi` 항은 Ordered Logit에서 {row_phrase(h3_ord)}, 대체 DV에서 {row_phrase(h3_alt)}, weighted OLS에서 {row_phrase(h3_w)}으로 나타나 주모형만큼 안정적이지 않은지 확인할 필요가 있다.",
    f"H4 Low DMI 하위집단에서 AI 활용 범위 단독항은 {row_phrase(h4)}으로 나타났다. 이는 탐색적 패턴으로 해석한다.",
    f"AI 측정 대체(`ai_use × it_org_any`) 분석에서는 {row_phrase(ai_alt)}으로 나타났다.",
    "전체적으로 방향과 유의성이 가장 안정적으로 유지되는 항은 H2 Headline의 AI 활용 범위 × IT 조직 보유 상호작용항인지 확인하는 데 초점을 둔다.",
    "모든 결과는 인과효과가 아니라 통제변수를 포함한 조건부 연관성으로 해석한다.",
]

alternative_robustness_interpretation_notes = "\n".join(f"- {line}" for line in interpretation_lines)
display(Markdown(alternative_robustness_interpretation_notes))

- H1은 Ordered Logit에서 + 방향, 유의성이 확인됨, 주모형과 방향·유의성 일치, 대체 DV 모형에서 + 방향, 유의성이 확인됨, 주모형과 방향·유의성 일치으로 나타났다.
- H2 Headline의 `ai_use_sum:it_org_any` 항은 Ordered Logit에서 + 방향, 유의성이 확인됨, 주모형과 방향·유의성 일치, 대체 DV에서 + 방향, 유의성이 확인됨, 주모형과 방향·유의성 일치, weighted OLS에서 + 방향, 유의성이 확인됨, 주모형과 방향·유의성 일치으로 확인된다.
- H3의 `ai_use_sum:dmi` 항은 Ordered Logit에서 + 방향, 유의성은 뚜렷하지 않음, 주모형과 방향·유의성 일치, 대체 DV에서 + 방향, 유의성이 확인됨, 방향은 일치하나 유의성은 약함, weighted OLS에서 + 방향, 유의성은 뚜렷하지 않음, 주모형과 방향·유의성 일치으로 나타나 주모형만큼 안정적이지 않은지 확인할 필요가 있다.
- H4 Low DMI 하위집단에서 AI 활용 범위 단독항은 - 방향, 유의성은 뚜렷하지 않음, 탐색적 결과으로 나타났다. 이는 탐색적 패턴으로 해석한다.
- AI 측정 대체(`ai_use × it_org_any`) 분석에서는 + 방향, 유의성이 확인됨, 주모형과 방향·유의성 일치으로 나타났다.
- 전체적으로 방향과 유의성이 가장 안정적으로 유지되는 항은 H2 Headline의 AI 활용 범위 × IT 조직 보유 상호작용항인지 확인하는 데 초점을 둔다.
- 모든 결과는 인과효과가 아니라 통제변수를 포함한 조건부 연관성으로 해석한다.

## 15. 저장

In [34]:
if SAVE_OUTPUTS:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    alternative_robustness_results_long.to_csv(TABLE_DIR / "alternative_robustness_results_long.csv", index=False, encoding="utf-8-sig")
    alternative_robustness_results_long.to_excel(TABLE_DIR / "alternative_robustness_results_long.xlsx", index=False)

    report_table.to_csv(TABLE_DIR / "alternative_robustness_report_table.csv", index=False, encoding="utf-8-sig")
    report_table.to_excel(TABLE_DIR / "alternative_robustness_report_table.xlsx", index=False)

    alternative_robustness_fit_stats.to_csv(TABLE_DIR / "alternative_robustness_fit_stats.csv", index=False, encoding="utf-8-sig")
    alternative_robustness_fit_stats.to_excel(TABLE_DIR / "alternative_robustness_fit_stats.xlsx", index=False)

    (MODEL_DIR / "alternative_robustness_full_summary.txt").write_text("\n\n".join(MAIN_FULL_SUMMARIES + FULL_SUMMARIES), encoding="utf-8")
    (OUTPUT_DIR / "alternative_robustness_interpretation_notes.txt").write_text(alternative_robustness_interpretation_notes, encoding="utf-8")

    with pd.ExcelWriter(OUTPUT_DIR / "alternative_robustness_summary.xlsx") as writer:
        variable_check.to_excel(writer, sheet_name="variable_check", index=False)
        main_reference_table.to_excel(writer, sheet_name="main_reference", index=False)
        TABLES.get("ordered_logit", pd.DataFrame()).to_excel(writer, sheet_name="ordered_logit", index=False)
        TABLES.get("alternative_dv", pd.DataFrame()).to_excel(writer, sheet_name="alternative_dv", index=False)
        TABLES.get("weighted_ols", pd.DataFrame()).to_excel(writer, sheet_name="weighted_ols", index=False)
        TABLES.get("low_dmi_subsample", pd.DataFrame()).to_excel(writer, sheet_name="low_dmi_subsample", index=False)
        TABLES.get("alternative_ai_measure", pd.DataFrame()).to_excel(writer, sheet_name="alternative_ai_measure", index=False)
        alternative_robustness_results_long.to_excel(writer, sheet_name="long_results", index=False)
        report_table.to_excel(writer, sheet_name="report_table", index=False)
        alternative_robustness_fit_stats.to_excel(writer, sheet_name="fit_stats", index=False)

    print("저장 완료:", OUTPUT_DIR.relative_to(BASE_DIR))
else:
    print("SAVE_OUTPUTS=False이므로 파일 저장은 수행하지 않았습니다.")

저장 완료: outputs/09_alternative_robustness_models

## 16. 실행 요약

In [35]:
print("사용 데이터 파일:", DATA_PATH.relative_to(BASE_DIR))
print("데이터 shape:", LOADED_SHAPE)
print("생성 결과 행 수:", len(alternative_robustness_results_long))
print("fit stats 행 수:", len(alternative_robustness_fit_stats))
print("SAVE_OUTPUTS:", SAVE_OUTPUTS)
if SAVE_OUTPUTS:
    print("결과 저장 폴더:", OUTPUT_DIR.relative_to(BASE_DIR))

사용 데이터 파일: working/analysis/nia_2024_analysis_total.csv
데이터 shape: (12203, 103)
생성 결과 행 수: 23
fit stats 행 수: 23
SAVE_OUTPUTS: True
결과 저장 폴더: outputs/09_alternative_robustness_models